---
- name: Test js-sdk play
  hosts: localhost
  tasks:
    - name: "test pool creation"
      pool: 
        farm_name: lochristi_dev_lab
        wallet_name: mainnet
      register: result

    - debug:
        msg: "pool id: {{ result['message']['reservation_id'] }}"

    - name: "test pool extension"
      pool: 
        pool_id: "{{ result['message']['reservation_id'] }}"
        wallet_name: mainnet
        sus: 100
        cus: 50