---
- name: Test js-sdk play
  hosts: localhost
  tasks:

    - name: "pool reservation"
      threefold.jsgrid.pool: 
        pool_id: 226
        wallet_name: mainnet
        ipv4us: 600
      register: result

    - debug:
        msg: "pool id: {{ result['message']['reservation_id'] }}"

    - name: "test public ip creation"
      threefold.jsgrid.public_ip: 
        identity_name: testnet
        pool_id: 226
        node_id: HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE
        ip_address: "185.69.167.143/24"
      register: result
    
    - debug:
        msg: "result is: {{ result }}"